# Generated by Django 5.2.5 on 2025-08-23 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_domain_remove_customer_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_count', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='rental',
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('best_seller', 'Best Seller'), ('new_arrival', 'New Arrival'), ('sale', 'Sale'), ('popular', 'Popular'), ('limited', 'Limited'), ('out_of_stock', 'Out of Stock')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='companies.category'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='companies.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='My Store', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_subtitle', models.TextField(blank=True, null=True)),
                ('hero_image', models.URLField(blank=True, max_length=500, null=True)),
                ('cta_text', models.CharField(default='Shop Now', max_length=100)),
                ('business_type', models.CharField(choices=[('electronics', 'Electronics & Technology'), ('fashion', 'Fashion Boutique'), ('home_garden', 'Home & Garden'), ('sports', 'Sports Equipment'), ('books_media', 'Books & Media'), ('handmade', 'Handmade Crafts'), ('other', 'Other Retail')], default='electronics', max_length=100)),
                ('primary_color', models.CharField(default='blue', max_length=20)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('classic', 'Classic')], default='modern', max_length=50)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_config', to='companies.client')),
            ],
            options={
                'db_table': 'store_config',
            },
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
