# Generated by Django 5.2.5 on 2025-08-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_category_remove_order_rental_product_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_configs', to='companies.company'),
        ),
    ]
