# Generated by Django 5.2.5 on 2025-08-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_storeconfig_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
